SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
COMMENT ON SCHEMA "public" IS 'standard public schema';
CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";
SET default_tablespace = '';
SET default_table_access_method = "heap";
CREATE TABLE IF NOT EXISTS "public"."activity_definitions" (
    "id" bigint NOT NULL,
    "category" "text" NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "activity_order" smallint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "category_order" smallint,
    "is_stock_activity" boolean,
    "active" boolean DEFAULT true NOT NULL
);
ALTER TABLE "public"."activity_definitions" OWNER TO "postgres";
ALTER TABLE "public"."activity_definitions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."activity_definitions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."activity_status" (
    "id" bigint NOT NULL,
    "purchase_id" bigint,
    "container_id" bigint,
    "sales_id" bigint,
    "assigned_to" bigint,
    "completed_by" bigint,
    "completed_at" timestamp with time zone,
    "due_date" timestamp with time zone,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "activity_status_reference_check" CHECK ((("purchase_id" IS NOT NULL) OR ("container_id" IS NOT NULL) OR ("sales_id" IS NOT NULL)))
);
ALTER TABLE "public"."activity_status" OWNER TO "postgres";
ALTER TABLE "public"."activity_status" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."activity_status_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."containers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "date_departure_target" timestamp with time zone,
    "date_departure_estimated" timestamp with time zone,
    "date_arrival_target" timestamp with time zone,
    "date_arrival_estimated" timestamp with time zone,
    "port_loading" "text",
    "port_destination" "text",
    "container_number" "text",
    "bill_of_lading_number" "text",
    "seal_number" "text",
    "booking_number" "text",
    "company" "text",
    "date_departure_confirmed" boolean DEFAULT false NOT NULL,
    "date_arrival_confirmed" boolean DEFAULT false NOT NULL
);
ALTER TABLE "public"."containers" OWNER TO "postgres";
COMMENT ON TABLE "public"."containers" IS 'Physical sea containers';
COMMENT ON COLUMN "public"."containers"."company" IS 'Which transport company is used?';
ALTER TABLE "public"."containers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."containers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."customers" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "number" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "name" "text",
    "shortened" "text"
);
ALTER TABLE "public"."customers" OWNER TO "postgres";
COMMENT ON COLUMN "public"."customers"."shortened" IS 'A shortened customer name';
CREATE TABLE IF NOT EXISTS "public"."purchase_containers_connections" (
    "id" bigint NOT NULL,
    "purchase_id" bigint NOT NULL,
    "container_id" bigint NOT NULL,
    "quantity_in_container" numeric,
    "created_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."purchase_containers_connections" OWNER TO "postgres";
ALTER TABLE "public"."purchase_containers_connections" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."purchase_containers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."purchase_sales_connections" (
    "id" bigint NOT NULL,
    "purchase_id" bigint,
    "sales_id" bigint,
    "quantity_linked" numeric,
    "link_type" "text",
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."purchase_sales_connections" OWNER TO "postgres";
ALTER TABLE "public"."purchase_sales_connections" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."purchase_sales_links_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."purchases" (
    "id" bigint NOT NULL,
    "po_number" integer,
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "quantity" numeric,
    "purchased_by" bigint,
    "managed_by" bigint,
    "incoterm" "text",
    "supplier_number" integer,
    "active" boolean DEFAULT false,
    "checklist" "jsonb" DEFAULT '[]'::"jsonb",
    "inactive_since" timestamp with time zone
);
ALTER TABLE "public"."purchases" OWNER TO "postgres";
COMMENT ON TABLE "public"."purchases" IS 'Stores all purchase orders';
COMMENT ON COLUMN "public"."purchases"."purchased_by" IS 'The person who purchased this purchase';
COMMENT ON COLUMN "public"."purchases"."managed_by" IS 'The person who manages this purchase';
COMMENT ON COLUMN "public"."purchases"."supplier_number" IS 'The supplier providing these goods.';
COMMENT ON COLUMN "public"."purchases"."checklist" IS 'Temporary until we use activity_status';
ALTER TABLE "public"."purchases" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."purchases_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."sales" (
    "id" bigint NOT NULL,
    "so_number" integer,
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "quantity" numeric,
    "sold_by" bigint,
    "managed_by" bigint,
    "is_stock" boolean,
    "incoterm" "text",
    "customer_number" integer,
    "active" boolean DEFAULT false,
    "checklist" "jsonb" DEFAULT '[]'::"jsonb",
    "inactive_since" timestamp with time zone
);
ALTER TABLE "public"."sales" OWNER TO "postgres";
COMMENT ON TABLE "public"."sales" IS 'Stores all sales orders';
COMMENT ON COLUMN "public"."sales"."customer_number" IS 'The customer of this sales order.';
ALTER TABLE "public"."sales" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sales_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."suppliers" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "number" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "name" "text"
);
ALTER TABLE "public"."suppliers" OWNER TO "postgres";
COMMENT ON TABLE "public"."suppliers" IS 'Froconsur suppliers';
CREATE TABLE IF NOT EXISTS "public"."updates" (
    "id" bigint NOT NULL,
    "purchase_id" bigint,
    "sales_id" bigint,
    "container_id" bigint,
    "activity_status_id" bigint,
    "comment" "text" NOT NULL,
    "update_type" "text" DEFAULT 'comment'::"text",
    "created_by" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "is_human" boolean DEFAULT true,
    "is_pinned" boolean DEFAULT false NOT NULL,
    "original_workflowapp_id" integer,
    CONSTRAINT "updates_reference_check" CHECK ((("purchase_id" IS NOT NULL) OR ("sales_id" IS NOT NULL) OR ("container_id" IS NOT NULL) OR ("activity_status_id" IS NOT NULL)))
);
ALTER TABLE "public"."updates" OWNER TO "postgres";
COMMENT ON COLUMN "public"."updates"."is_human" IS 'Is the update generated by a human?';
ALTER TABLE "public"."updates" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."updates_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" bigint NOT NULL,
    "email" "text",
    "avatar_url" "text",
    "role" "text",
    "first_name" "text",
    "last_name" "text",
    "original_emp_id" smallint,
    "slack_id" "text",
    "retool_id" integer
);
ALTER TABLE "public"."users" OWNER TO "postgres";
COMMENT ON COLUMN "public"."users"."original_emp_id" IS 'The original Exact Globe employee ID';
ALTER TABLE "public"."users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY "public"."activity_definitions"
    ADD CONSTRAINT "activity_definitions_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."activity_status"
    ADD CONSTRAINT "activity_status_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."containers"
    ADD CONSTRAINT "containers_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."customers"
    ADD CONSTRAINT "customers_number_key" UNIQUE ("number");
ALTER TABLE ONLY "public"."customers"
    ADD CONSTRAINT "customers_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."purchase_containers_connections"
    ADD CONSTRAINT "purchase_containers_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."purchase_containers_connections"
    ADD CONSTRAINT "purchase_containers_unique" UNIQUE ("purchase_id", "container_id");
ALTER TABLE ONLY "public"."purchase_sales_connections"
    ADD CONSTRAINT "purchase_sales_links_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."purchase_sales_connections"
    ADD CONSTRAINT "purchase_sales_links_purchase_id_sales_id_key" UNIQUE ("purchase_id", "sales_id");
ALTER TABLE ONLY "public"."purchases"
    ADD CONSTRAINT "purchases_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."purchases"
    ADD CONSTRAINT "purchases_po_number_key" UNIQUE ("po_number");
ALTER TABLE ONLY "public"."sales"
    ADD CONSTRAINT "sales_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."sales"
    ADD CONSTRAINT "sales_so_number_key" UNIQUE ("so_number");
ALTER TABLE ONLY "public"."suppliers"
    ADD CONSTRAINT "suppliers_number_key" UNIQUE ("number");
ALTER TABLE ONLY "public"."suppliers"
    ADD CONSTRAINT "suppliers_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."updates"
    ADD CONSTRAINT "updates_original_workflowapp_id_key" UNIQUE ("original_workflowapp_id");
ALTER TABLE ONLY "public"."updates"
    ADD CONSTRAINT "updates_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_original_emp_id_key" UNIQUE ("original_emp_id");
ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");
CREATE INDEX "idx_activity_definitions_category" ON "public"."activity_definitions" USING "btree" ("category");
CREATE INDEX "idx_activity_definitions_sort_order" ON "public"."activity_definitions" USING "btree" ("activity_order");
CREATE INDEX "idx_activity_status_assigned_to" ON "public"."activity_status" USING "btree" ("assigned_to");
CREATE INDEX "idx_activity_status_container_id" ON "public"."activity_status" USING "btree" ("container_id");
CREATE INDEX "idx_activity_status_purchase_id" ON "public"."activity_status" USING "btree" ("purchase_id");
CREATE INDEX "idx_activity_status_sales_id" ON "public"."activity_status" USING "btree" ("sales_id");
CREATE INDEX "idx_updates_activity_status_id" ON "public"."updates" USING "btree" ("activity_status_id");
CREATE INDEX "idx_updates_container_id" ON "public"."updates" USING "btree" ("container_id");
CREATE INDEX "idx_updates_created_at" ON "public"."updates" USING "btree" ("created_at" DESC);
CREATE INDEX "idx_updates_created_by" ON "public"."updates" USING "btree" ("created_by");
CREATE INDEX "idx_updates_purchase_id" ON "public"."updates" USING "btree" ("purchase_id");
CREATE INDEX "idx_updates_sales_id" ON "public"."updates" USING "btree" ("sales_id");
CREATE INDEX "idx_updates_update_type" ON "public"."updates" USING "btree" ("update_type");
ALTER TABLE ONLY "public"."activity_status"
    ADD CONSTRAINT "activity_status_assigned_to_fkey" FOREIGN KEY ("assigned_to") REFERENCES "public"."users"("id");
ALTER TABLE ONLY "public"."activity_status"
    ADD CONSTRAINT "activity_status_completed_by_fkey" FOREIGN KEY ("completed_by") REFERENCES "public"."users"("id");
ALTER TABLE ONLY "public"."activity_status"
    ADD CONSTRAINT "activity_status_container_id_fkey" FOREIGN KEY ("container_id") REFERENCES "public"."containers"("id");
ALTER TABLE ONLY "public"."activity_status"
    ADD CONSTRAINT "activity_status_purchase_id_fkey" FOREIGN KEY ("purchase_id") REFERENCES "public"."purchases"("id");
ALTER TABLE ONLY "public"."activity_status"
    ADD CONSTRAINT "activity_status_sales_id_fkey" FOREIGN KEY ("sales_id") REFERENCES "public"."sales"("id");
ALTER TABLE ONLY "public"."purchase_containers_connections"
    ADD CONSTRAINT "purchase_containers_container_id_fkey" FOREIGN KEY ("container_id") REFERENCES "public"."containers"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."purchase_containers_connections"
    ADD CONSTRAINT "purchase_containers_purchase_id_fkey" FOREIGN KEY ("purchase_id") REFERENCES "public"."purchases"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."purchase_sales_connections"
    ADD CONSTRAINT "purchase_sales_links_purchase_id_fkey" FOREIGN KEY ("purchase_id") REFERENCES "public"."purchases"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."purchase_sales_connections"
    ADD CONSTRAINT "purchase_sales_links_sales_id_fkey" FOREIGN KEY ("sales_id") REFERENCES "public"."sales"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."purchases"
    ADD CONSTRAINT "purchases_managed_by_fkey" FOREIGN KEY ("managed_by") REFERENCES "public"."users"("id");
ALTER TABLE ONLY "public"."purchases"
    ADD CONSTRAINT "purchases_purchased_by_fkey" FOREIGN KEY ("purchased_by") REFERENCES "public"."users"("id");
ALTER TABLE ONLY "public"."purchases"
    ADD CONSTRAINT "purchases_supplier_number_fkey" FOREIGN KEY ("supplier_number") REFERENCES "public"."suppliers"("number");
ALTER TABLE ONLY "public"."sales"
    ADD CONSTRAINT "sales_customer_number_fkey" FOREIGN KEY ("customer_number") REFERENCES "public"."customers"("number");
ALTER TABLE ONLY "public"."sales"
    ADD CONSTRAINT "sales_managed_by_fkey" FOREIGN KEY ("managed_by") REFERENCES "public"."users"("id");
ALTER TABLE ONLY "public"."sales"
    ADD CONSTRAINT "sales_sold_by_fkey" FOREIGN KEY ("sold_by") REFERENCES "public"."users"("id");
ALTER TABLE ONLY "public"."updates"
    ADD CONSTRAINT "updates_activity_status_id_fkey" FOREIGN KEY ("activity_status_id") REFERENCES "public"."activity_status"("id");
ALTER TABLE ONLY "public"."updates"
    ADD CONSTRAINT "updates_container_id_fkey" FOREIGN KEY ("container_id") REFERENCES "public"."containers"("id");
ALTER TABLE ONLY "public"."updates"
    ADD CONSTRAINT "updates_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id");
ALTER TABLE ONLY "public"."updates"
    ADD CONSTRAINT "updates_purchase_id_fkey" FOREIGN KEY ("purchase_id") REFERENCES "public"."purchases"("id");
ALTER TABLE ONLY "public"."updates"
    ADD CONSTRAINT "updates_sales_id_fkey" FOREIGN KEY ("sales_id") REFERENCES "public"."sales"("id");
ALTER TABLE "public"."activity_definitions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."activity_status" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."containers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."customers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."purchase_containers_connections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."purchase_sales_connections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."purchases" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."sales" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."suppliers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."updates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;
ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";
GRANT ALL ON TABLE "public"."activity_definitions" TO "anon";
GRANT ALL ON TABLE "public"."activity_definitions" TO "authenticated";
GRANT ALL ON TABLE "public"."activity_definitions" TO "service_role";
GRANT ALL ON SEQUENCE "public"."activity_definitions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."activity_definitions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."activity_definitions_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."activity_status" TO "anon";
GRANT ALL ON TABLE "public"."activity_status" TO "authenticated";
GRANT ALL ON TABLE "public"."activity_status" TO "service_role";
GRANT ALL ON SEQUENCE "public"."activity_status_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."activity_status_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."activity_status_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."containers" TO "anon";
GRANT ALL ON TABLE "public"."containers" TO "authenticated";
GRANT ALL ON TABLE "public"."containers" TO "service_role";
GRANT ALL ON SEQUENCE "public"."containers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."containers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."containers_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."customers" TO "anon";
GRANT ALL ON TABLE "public"."customers" TO "authenticated";
GRANT ALL ON TABLE "public"."customers" TO "service_role";
GRANT ALL ON TABLE "public"."purchase_containers_connections" TO "anon";
GRANT ALL ON TABLE "public"."purchase_containers_connections" TO "authenticated";
GRANT ALL ON TABLE "public"."purchase_containers_connections" TO "service_role";
GRANT ALL ON SEQUENCE "public"."purchase_containers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."purchase_containers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."purchase_containers_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."purchase_sales_connections" TO "anon";
GRANT ALL ON TABLE "public"."purchase_sales_connections" TO "authenticated";
GRANT ALL ON TABLE "public"."purchase_sales_connections" TO "service_role";
GRANT ALL ON SEQUENCE "public"."purchase_sales_links_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."purchase_sales_links_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."purchase_sales_links_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."purchases" TO "anon";
GRANT ALL ON TABLE "public"."purchases" TO "authenticated";
GRANT ALL ON TABLE "public"."purchases" TO "service_role";
GRANT ALL ON SEQUENCE "public"."purchases_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."purchases_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."purchases_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."sales" TO "anon";
GRANT ALL ON TABLE "public"."sales" TO "authenticated";
GRANT ALL ON TABLE "public"."sales" TO "service_role";
GRANT ALL ON SEQUENCE "public"."sales_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sales_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sales_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."suppliers" TO "anon";
GRANT ALL ON TABLE "public"."suppliers" TO "authenticated";
GRANT ALL ON TABLE "public"."suppliers" TO "service_role";
GRANT ALL ON TABLE "public"."updates" TO "anon";
GRANT ALL ON TABLE "public"."updates" TO "authenticated";
GRANT ALL ON TABLE "public"."updates" TO "service_role";
GRANT ALL ON SEQUENCE "public"."updates_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."updates_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."updates_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";
drop extension if exists "pg_net";
