CREATE TABLE "activityDefinitions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category" text NOT NULL DEFAULT false,
  "name" text NOT NULL DEFAULT false,
  "description" text,
  "activityOrder" smallint NOT NULL DEFAULT false,
  "createdAt" timestamptz DEFAULT (now()),
  "updatedAt" timestamptz DEFAULT (now()),
  "categoryOrder" smallint,
  "isStockActivity" boolean,
  "active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "activityStatus" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "purchaseID" bigint,
  "containerID" bigint,
  "salesID" bigint,
  "assignedTo" bigint,
  "completedBy" bigint,
  "completedAt" timestamptz,
  "dueDate" timestamptz,
  "notes" text,
  "createdAt" timestamptz,
  "updatedAt" timestamptz
);

CREATE TABLE "containers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "createdOn" datetime,
  "updatedAt" datetime,
  "updatedBy" bigint,
  "calculationName" text,
  "portOfLoading" text,
  "portOfDestination" text,
  "containerNumber" text,
  "BLnumber" text,
  "sealNumber" text,
  "bookingNumber" text,
  "company" text,
  "dateDepartureConfirmed" boolean,
  "dateArrivalConfirmed" boolean,
  "docCheckListID" bigint
);

CREATE TABLE "shippingPorts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text,
  "UN_LOCODE" text,
  "country" text,
  "city" text
);

CREATE TABLE "shippingCompanies" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text,
  "active" bool,
  "loginURL" url,
  "userName" varchar,
  "password" varchar,
  "comments" text,
  "createdBy" bigint,
  "updateBy" bigint
);

CREATE TABLE "coldStore" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text,
  "contactPersonName" text,
  "contactPersonPhoneNumber" int,
  "contactPersonEmail" email,
  "webURL" url,
  "address" text,
  "city" text,
  "country" text,
  "postCode" varchar,
  "active" bool,
  "loginURL" url,
  "userName" varchar,
  "password" varchar,
  "comments" text,
  "createdBy" bigint,
  "updateBy" bigint
);

CREATE TABLE "customsAgent" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text,
  "contactPersonName" text,
  "contactPersonPhoneNumber" int,
  "contactPersonEmail" email,
  "webURL" url,
  "address" text,
  "city" text,
  "country" text,
  "postCode" varchar,
  "active" bool,
  "loginURL" url,
  "userName" varchar,
  "password" varchar,
  "comments" text,
  "createdBy" bigint,
  "updateBy" bigint
);

CREATE TABLE "customers" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "number" integer UNIQUE,
  "createdAt" timestamptz DEFAULT (now()),
  "updatedAt" timestamp,
  "name" text,
  "shortened" text,
  "updatedBy" bigint
);

CREATE TABLE "customerPaymentTerms" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "code" integer UNIQUE,
  "percAdvancePayment" float,
  "paymentDays" integer,
  "condition" text
);

CREATE TABLE "supplierPaymentTerms" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "code" integer UNIQUE,
  "percAdvancePayment" float,
  "condition" text
);

CREATE TABLE "purchaseContainersConnections" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "purchaseID" bigint,
  "containerID" bigint,
  "quantityInContainer" numeric,
  "createdAt" timestamptz DEFAULT (now()),
  "updatedBy" bigint
);

CREATE TABLE "Calculation" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "notes" text,
  "purchaseProposalID" list,
  "salesProposalID" list,
  "sheetType" text,
  "createdAt" timestamptz DEFAULT (now()),
  "createdBy" bigint,
  "updatedAt" timestamptz DEFAULT (now()),
  "updatedBy" bigint,
  "status" text,
  "approvedBy" bigint
);

CREATE TABLE "purchase" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CalculationName" varchar,
  "poNumber" integer UNIQUE,
  "createdAt" timestamptz DEFAULT (now()),
  "createdBy" bigint,
  "updatedAt" timestamp,
  "updatedBy" bigint,
  "salesManager" bigint,
  "approvedBy" bigint,
  "scmManager" bigint,
  "status" text,
  "active" boolean DEFAULT false,
  "checklist" jsonb DEFAULT ([])
);

CREATE TABLE "sales" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CalculationName" varchar,
  "soNumber" integer UNIQUE,
  "createdAt" timestamptz DEFAULT (now()),
  "createdBy" bigint,
  "soldBy" bigint,
  "approvedBy" bigint,
  "salesManager" bigint,
  "supplyChainManager" bigint,
  "active" boolean DEFAULT false,
  "checklist" jsonb DEFAULT ([]),
  "status" text
);

CREATE TABLE "suppliers" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "number" integer UNIQUE,
  "createdAt" timestamptz DEFAULT (now()),
  "name" text
);

CREATE TABLE "purchaseSalesAgents" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text,
  "contactNumber" bigint,
  "country" text,
  "salesORpurchaseORboth" text
);

CREATE TABLE "updates" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "purchaseID" bigint,
  "salesID" bigint,
  "containerID" bigint,
  "activityStatusID" bigint,
  "comment" text,
  "updateType" text DEFAULT (comment),
  "updatedBy" bigint,
  "createdBy" bigint,
  "createdAt" timestamptz DEFAULT (now()),
  "updatedAt" timestamptz DEFAULT (now()),
  "isHuman" boolean DEFAULT true,
  "isPinned" boolean DEFAULT false,
  "originalWorkflowappID" integer UNIQUE
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" text,
  "avatarUrl" text,
  "role" text,
  "firstName" text,
  "lastName" text,
  "originalEmpID" smallint UNIQUE,
  "slackID" text,
  "retoolID" integer,
  "active" bool
);

CREATE TABLE "articles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "articleCode" varchar,
  "description" varchar,
  "L1Code" int,
  "L2Code" int,
  "L3Code" int,
  "L4Code" int,
  "L5Code" int,
  "L6Code" int
);

CREATE TABLE "ArticleGroupScientificName" (
  "L1Code" int PRIMARY KEY,
  "articleGroup" text,
  "scientificName" text,
  "hscode" int
);

CREATE TABLE "ArticleProcessing" (
  "L1Code" int,
  "L2Code" int PRIMARY KEY,
  "processing" varchar
);

CREATE TABLE "ArticleSize" (
  "L1Code" int,
  "L2Code" int,
  "L3Code" int PRIMARY KEY,
  "size" varchar
);

CREATE TABLE "ArticleFreezingType" (
  "L4Code" int PRIMARY KEY,
  "freezingType" varchar
);

CREATE TABLE "ArticleRealGlaze" (
  "L5Code" int,
  "realGlaze" int PRIMARY KEY
);

CREATE TABLE "ArticlePackaging" (
  "L6Code" varchar PRIMARY KEY,
  "brand" varchar,
  "printedGlaze" int,
  "unitWeight" float,
  "BagBoxBulk" text,
  "unitsInBox" int,
  "printedPlainRider" text,
  "labelsLink" link
);

CREATE TABLE "purchaseOrderLines" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "articlecode" int,
  "purchasePricePerKG" float,
  "netWeightKG" float,
  "frozenWeightKG" float,
  "grossWeight" float,
  "createdAt" timestamp,
  "createdBy" bigint,
  "updatedAt" timestamp,
  "updatedBy" bigint
);

CREATE TABLE "status" (
  "status" text
);

CREATE TABLE "salesOrderLines" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "articleCode" int,
  "salesPricePerKG" int,
  "netWeightKG" float,
  "frozenWeightKG" float,
  "grossWeight" float,
  "createdAt" timestamp,
  "createdBy" bigint,
  "updatedAt" timestamp,
  "updatedBy" bigint
);

CREATE TABLE "salesPurchaseProposal" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "purchaseProposalID" bigint,
  "salesProposalID" bigint,
  "conversionRateEURtoUSD" float,
  "updatedOn" datetime,
  "updatedBy" bigint
);

CREATE TABLE "purchaseProposal" (
  "purchaseProposalID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE NOT NULL,
  "purchaseOrderlineID" bigint NOT NULL,
  "netQuantity" float,
  "frozenQuantity" float,
  "grossQuantity" float,
  "currency" text,
  "purchaseCost" float,
  "paymentTerms" varchar,
  "purchaseIncoTerms" varchar,
  "supplierName" text,
  "portOfLoading" text,
  "estimatedETA" date,
  "estimatedETD" date,
  "portOfClerence" text,
  "portOfDestination" text,
  "purchaseAgentName" bigint,
  "otherEstimatedPurchaseCostsID" bigint,
  "otherActualPurchaseCostsID" bigint,
  "status" text,
  "createdOn" datetime,
  "createdBy" bigint,
  "updatedOn" datetime,
  "updatedBy" bigint
);

CREATE TABLE "salesProposal" (
  "salesProposalID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customerName" text,
  "salesOrderlineID" bigint,
  "netQuantity" float,
  "frozenQuantity" float,
  "grossQuantity" float,
  "currency" text,
  "sellingCost" float,
  "paymentTerms" varchar,
  "salesIncoTerms" varchar,
  "estimatedDelivaryDate" date,
  "deliverFrom" text,
  "deliverTo" text,
  "otherEstimatedSalesCostsID" bigint,
  "otherActualSalesCostsID" bigint,
  "status" text,
  "updatedOn" datetime,
  "updatedBy" bigint,
  "salesAgentName" text
);

CREATE TABLE "otherEstimatedPurchaseCosts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agentComission" float,
  "purchaseProposalID" bigint,
  "freightCosts" float,
  "importDuties" float,
  "insuranceCosts" float,
  "bankCosts" float,
  "customsAgentCosts" float,
  "inspectionCosts" float
);

CREATE TABLE "otherActualPurchaseCosts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agentComission" float,
  "purchaseProposalID" bigint,
  "freightCosts" float,
  "importDuties" float,
  "insuranceCosts" float,
  "bankCosts" float,
  "customsAgentCosts" float,
  "inspectionCosts" float
);

CREATE TABLE "otherEstimatedSalesCosts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "salesProposalID" bigint,
  "coldStoreCosts" float,
  "truckCosts" float,
  "bankCosts" float,
  "insuranceCosts" float,
  "salesComission" float
);

CREATE TABLE "otherActualSalesCosts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "salesProposalID" bigint,
  "coldStoreCosts" float,
  "truckCosts" float,
  "bankCosts" float,
  "insuranceCosts" float,
  "salesComission" float
);

CREATE TABLE "commercialInvoiceOrderLines" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "purchaseOrderLineID" bigint,
  "articleID" bigint,
  "artworkID" bigint,
  "netWeightKG" float,
  "frozenWeightKG" float,
  "grossWeight" float,
  "createdAt" timestamp,
  "createdBy" bigint,
  "updatedAt" timestamp,
  "updatedBy" bigint
);

CREATE TABLE "intakeOrderLines" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "commercialInvoiceOrderLinesID" bigint,
  "coldStoreID" bigint,
  "inktakeDate" date,
  "poNumber" bigint,
  "containerNumber" bigint,
  "articleID" bigint,
  "artworkID" bigint,
  "netWeightKG" float,
  "frozenWeightKG" float,
  "grossWeight" float,
  "createdAt" timestamp,
  "createdBy" bigint,
  "updatedAt" timestamp,
  "updatedBy" bigint
);

CREATE TABLE "outTakeOrderLines" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "coldStoreID" bigint,
  "outakeDate" date,
  "salesOrderLineID" bigint,
  "articleID" bigint,
  "artworkID" bigint,
  "netWeightKG" float,
  "frozenWeightKG" float,
  "grossWeight" float,
  "createdAt" timestamp,
  "createdBy" bigint,
  "updatedAt" timestamp,
  "updatedBy" bigint
);

ALTER TABLE "articles" ADD FOREIGN KEY ("L1Code") REFERENCES "ArticleGroupScientificName" ("L1Code");

ALTER TABLE "ArticleProcessing" ADD FOREIGN KEY ("L2Code") REFERENCES "articles" ("L2Code");

ALTER TABLE "ArticleSize" ADD FOREIGN KEY ("L3Code") REFERENCES "articles" ("L3Code");

ALTER TABLE "ArticleFreezingType" ADD FOREIGN KEY ("L4Code") REFERENCES "articles" ("L4Code");

ALTER TABLE "ArticleRealGlaze" ADD FOREIGN KEY ("L5Code") REFERENCES "articles" ("L5Code");

ALTER TABLE "ArticlePackaging" ADD FOREIGN KEY ("L6Code") REFERENCES "articles" ("L6Code");

ALTER TABLE "ArticleGroupScientificName" ADD FOREIGN KEY ("L1Code") REFERENCES "ArticleProcessing" ("L1Code");

ALTER TABLE "ArticleGroupScientificName" ADD FOREIGN KEY ("L1Code") REFERENCES "ArticleSize" ("L1Code");

ALTER TABLE "ArticleProcessing" ADD FOREIGN KEY ("L2Code") REFERENCES "ArticleSize" ("L2Code");

ALTER TABLE "activityStatus" ADD FOREIGN KEY ("assignedTo") REFERENCES "users" ("id");

ALTER TABLE "activityStatus" ADD FOREIGN KEY ("completedBy") REFERENCES "users" ("id");

ALTER TABLE "activityStatus" ADD FOREIGN KEY ("containerID") REFERENCES "containers" ("id");

ALTER TABLE "activityStatus" ADD FOREIGN KEY ("purchaseID") REFERENCES "purchase" ("id");

ALTER TABLE "activityStatus" ADD FOREIGN KEY ("salesID") REFERENCES "sales" ("id");

ALTER TABLE "updates" ADD FOREIGN KEY ("purchaseID") REFERENCES "purchase" ("id");

ALTER TABLE "updates" ADD FOREIGN KEY ("salesID") REFERENCES "sales" ("id");

ALTER TABLE "updates" ADD FOREIGN KEY ("containerID") REFERENCES "containers" ("id");

ALTER TABLE "updates" ADD FOREIGN KEY ("activityStatusID") REFERENCES "activityStatus" ("id");

ALTER TABLE "updates" ADD FOREIGN KEY ("createdBy") REFERENCES "users" ("id");

ALTER TABLE "updates" ADD FOREIGN KEY ("updatedBy") REFERENCES "users" ("id");

ALTER TABLE "containers" ADD FOREIGN KEY ("calculationName") REFERENCES "Calculation" ("name");

ALTER TABLE "containers" ADD FOREIGN KEY ("updatedBy") REFERENCES "users" ("id");

ALTER TABLE "containers" ADD FOREIGN KEY ("company") REFERENCES "shippingCompanies" ("id");

ALTER TABLE "purchaseContainersConnections" ADD FOREIGN KEY ("purchaseID") REFERENCES "purchase" ("id");

ALTER TABLE "purchaseContainersConnections" ADD FOREIGN KEY ("containerID") REFERENCES "containers" ("id");

ALTER TABLE "Calculation" ADD FOREIGN KEY ("createdBy") REFERENCES "users" ("id");

ALTER TABLE "Calculation" ADD FOREIGN KEY ("purchaseProposalID") REFERENCES "purchaseProposal" ("purchaseProposalID");

ALTER TABLE "Calculation" ADD FOREIGN KEY ("salesProposalID") REFERENCES "salesProposal" ("salesProposalID");

ALTER TABLE "Calculation" ADD FOREIGN KEY ("approvedBy") REFERENCES "users" ("id");

ALTER TABLE "salesPurchaseProposal" ADD FOREIGN KEY ("purchaseProposalID") REFERENCES "purchaseProposal" ("purchaseProposalID");

ALTER TABLE "salesPurchaseProposal" ADD FOREIGN KEY ("salesProposalID") REFERENCES "salesProposal" ("salesProposalID");

ALTER TABLE "purchase" ADD FOREIGN KEY ("CalculationName") REFERENCES "Calculation" ("name");

ALTER TABLE "purchase" ADD FOREIGN KEY ("status") REFERENCES "status" ("status");

ALTER TABLE "sales" ADD FOREIGN KEY ("CalculationName") REFERENCES "Calculation" ("name");

ALTER TABLE "sales" ADD FOREIGN KEY ("status") REFERENCES "status" ("status");

ALTER TABLE "purchaseOrderLines" ADD FOREIGN KEY ("articlecode") REFERENCES "articles" ("articleCode");

ALTER TABLE "purchaseOrderLines" ADD FOREIGN KEY ("createdBy") REFERENCES "users" ("id");

ALTER TABLE "purchaseOrderLines" ADD FOREIGN KEY ("updatedBy") REFERENCES "users" ("id");

ALTER TABLE "purchaseProposal" ADD FOREIGN KEY ("purchaseOrderlineID") REFERENCES "purchaseOrderLines" ("id");

ALTER TABLE "purchaseProposal" ADD FOREIGN KEY ("supplierName") REFERENCES "suppliers" ("name");

ALTER TABLE "purchaseProposal" ADD FOREIGN KEY ("purchaseAgentName") REFERENCES "purchaseSalesAgents" ("name");

ALTER TABLE "purchaseProposal" ADD FOREIGN KEY ("otherEstimatedPurchaseCostsID") REFERENCES "otherEstimatedPurchaseCosts" ("id");

ALTER TABLE "purchaseProposal" ADD FOREIGN KEY ("otherActualPurchaseCostsID") REFERENCES "otherActualPurchaseCosts" ("id");

ALTER TABLE "purchaseProposal" ADD FOREIGN KEY ("portOfLoading") REFERENCES "shippingPorts" ("name");

ALTER TABLE "purchaseProposal" ADD FOREIGN KEY ("portOfClerence") REFERENCES "shippingPorts" ("name");

ALTER TABLE "purchaseProposal" ADD FOREIGN KEY ("portOfDestination") REFERENCES "shippingPorts" ("name");

ALTER TABLE "purchaseProposal" ADD FOREIGN KEY ("status") REFERENCES "status" ("status");

ALTER TABLE "purchaseProposal" ADD FOREIGN KEY ("createdBy") REFERENCES "users" ("id");

ALTER TABLE "purchaseProposal" ADD FOREIGN KEY ("paymentTerms") REFERENCES "supplierPaymentTerms" ("code");

ALTER TABLE "salesProposal" ADD FOREIGN KEY ("salesOrderlineID") REFERENCES "salesOrderLines" ("id");

ALTER TABLE "salesProposal" ADD FOREIGN KEY ("customerName") REFERENCES "customers" ("name");

ALTER TABLE "salesProposal" ADD FOREIGN KEY ("salesAgentName") REFERENCES "purchaseSalesAgents" ("name");

ALTER TABLE "salesProposal" ADD FOREIGN KEY ("otherEstimatedSalesCostsID") REFERENCES "otherEstimatedSalesCosts" ("id");

ALTER TABLE "salesProposal" ADD FOREIGN KEY ("otherActualSalesCostsID") REFERENCES "otherActualSalesCosts" ("id");

ALTER TABLE "salesProposal" ADD FOREIGN KEY ("status") REFERENCES "status" ("status");

ALTER TABLE "salesProposal" ADD FOREIGN KEY ("paymentTerms") REFERENCES "customerPaymentTerms" ("code");

ALTER TABLE "salesOrderLines" ADD FOREIGN KEY ("articleCode") REFERENCES "articles" ("articleCode");

ALTER TABLE "salesOrderLines" ADD FOREIGN KEY ("createdBy") REFERENCES "users" ("id");

ALTER TABLE "salesOrderLines" ADD FOREIGN KEY ("updatedBy") REFERENCES "users" ("id");

ALTER TABLE "salesPurchaseProposal" ADD FOREIGN KEY ("updatedBy") REFERENCES "users" ("id");

ALTER TABLE "purchaseProposal" ADD FOREIGN KEY ("updatedBy") REFERENCES "users" ("id");

ALTER TABLE "salesProposal" ADD FOREIGN KEY ("updatedBy") REFERENCES "users" ("id");

ALTER TABLE "commercialInvoiceOrderLines" ADD FOREIGN KEY ("purchaseOrderLineID") REFERENCES "purchaseOrderLines" ("id");

ALTER TABLE "commercialInvoiceOrderLines" ADD FOREIGN KEY ("createdBy") REFERENCES "users" ("id");

ALTER TABLE "commercialInvoiceOrderLines" ADD FOREIGN KEY ("updatedBy") REFERENCES "users" ("id");

ALTER TABLE "intakeOrderLines" ADD FOREIGN KEY ("commercialInvoiceOrderLinesID") REFERENCES "commercialInvoiceOrderLines" ("id");

ALTER TABLE "intakeOrderLines" ADD FOREIGN KEY ("updatedBy") REFERENCES "users" ("id");

ALTER TABLE "intakeOrderLines" ADD FOREIGN KEY ("createdBy") REFERENCES "users" ("id");

ALTER TABLE "intakeOrderLines" ADD FOREIGN KEY ("coldStoreID") REFERENCES "coldStore" ("id");

ALTER TABLE "outTakeOrderLines" ADD FOREIGN KEY ("salesOrderLineID") REFERENCES "salesOrderLines" ("id");

ALTER TABLE "outTakeOrderLines" ADD FOREIGN KEY ("updatedBy") REFERENCES "users" ("id");

ALTER TABLE "outTakeOrderLines" ADD FOREIGN KEY ("createdBy") REFERENCES "users" ("id");

ALTER TABLE "outTakeOrderLines" ADD FOREIGN KEY ("coldStoreID") REFERENCES "coldStore" ("id");
