-- Date: 2026-02-10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

COMMENT ON SCHEMA "public" IS 'standard public schema';

-- Extensions
CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';
SET default_table_access_method = "heap";

-- =====================================================
-- CORE TABLES
-- =====================================================

-- Users table
CREATE TABLE IF NOT EXISTS "public"."users" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"email" text,
"avatarUrl" text,
"role" text,
"firstName" text,
"lastName" text,
"originalEmpID" smallint UNIQUE,
"slackID" text,
"retoolID" integer,
"active" boolean
);

ALTER TABLE "public"."users" OWNER TO "postgres";

-- Customers table
CREATE TABLE IF NOT EXISTS "public"."customers" (
"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
"number" integer UNIQUE NOT NULL,
"createdAt" timestamptz DEFAULT now(),
"updatedAt" timestamptz,
"name" text,
"shortened" text,
"updatedBy" bigint
);

ALTER TABLE "public"."customers" OWNER TO "postgres";
COMMENT ON COLUMN "public"."customers"."shortened" IS 'A shortened customer name';

-- Suppliers table
CREATE TABLE IF NOT EXISTS "public"."suppliers" (
"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
"number" integer UNIQUE NOT NULL,
"createdAt" timestamptz DEFAULT now(),
"name" text
);

ALTER TABLE "public"."suppliers" OWNER TO "postgres";
COMMENT ON TABLE "public"."suppliers" IS 'Froconsur suppliers';

-- Status lookup table
CREATE TABLE IF NOT EXISTS "public"."status" (
"status" text PRIMARY KEY
);

ALTER TABLE "public"."status" OWNER TO "postgres";

-- =====================================================
-- ACTIVITY MANAGEMENT TABLES
-- =====================================================

-- Activity definitions
CREATE TABLE IF NOT EXISTS "public"."activityDefinitions" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"category" text NOT NULL DEFAULT '',
"name" text NOT NULL DEFAULT '',
"description" text,
"activityOrder" smallint NOT NULL DEFAULT 0,
"createdAt" timestamptz DEFAULT now(),
"updatedAt" timestamptz DEFAULT now(),
"categoryOrder" smallint,
"isStockActivity" boolean,
"active" boolean NOT NULL DEFAULT true
);

ALTER TABLE "public"."activityDefinitions" OWNER TO "postgres";

-- Activity status
CREATE TABLE IF NOT EXISTS "public"."activityStatus" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"purchaseID" bigint,
"containerID" bigint,
"salesID" bigint,
"assignedTo" bigint,
"completedBy" bigint,
"completedAt" timestamptz,
"dueDate" timestamptz,
"notes" text,
"createdAt" timestamptz DEFAULT now(),
"updatedAt" timestamptz DEFAULT now(),
CONSTRAINT "activityStatus_reference_check" CHECK (
("purchaseID" IS NOT NULL) OR
("containerID" IS NOT NULL) OR
("salesID" IS NOT NULL)
)
);

ALTER TABLE "public"."activityStatus" OWNER TO "postgres";

-- =====================================================
-- CALCULATION AND PROPOSAL TABLES
-- =====================================================

-- Calculation table
CREATE TABLE IF NOT EXISTS "public"."Calculation" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" varchar UNIQUE,
"notes" text,
"purchaseProposalID" bigint,
"salesProposalID" bigint,
"sheetType" text,
"createdAt" timestamptz DEFAULT now(),
"createdBy" bigint,
"updatedAt" timestamptz DEFAULT now(),
"updatedBy" bigint,
"status" text,
"approvedBy" bigint
);

ALTER TABLE "public"."Calculation" OWNER TO "postgres";

-- Purchase proposal
CREATE TABLE IF NOT EXISTS "public"."purchaseProposal" (
"purchaseProposalID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" text UNIQUE NOT NULL,
"purchaseOrderlineID" bigint NOT NULL,
"netQuantity" float,
"frozenQuantity" float,
"grossQuantity" float,
"currency" text,
"purchaseCost" float,
"paymentTerms" varchar,
"purchaseIncoTerms" varchar,
"supplierName" text,
"portOfLoading" text,
"estimatedETA" date,
"estimatedETD" date,
"portOfClerence" text,
"portOfDestination" text,
"purchaseAgentName" bigint,
"otherEstimatedPurchaseCostsID" bigint,
"otherActualPurchaseCostsID" bigint,
"status" text,
"createdOn" timestamptz,
"createdBy" bigint,
"updatedOn" timestamptz,
"updatedBy" bigint
);

ALTER TABLE "public"."purchaseProposal" OWNER TO "postgres";

-- Sales proposal
CREATE TABLE IF NOT EXISTS "public"."salesProposal" (
"salesProposalID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"customerName" text,
"salesOrderlineID" bigint,
"netQuantity" float,
"frozenQuantity" float,
"grossQuantity" float,
"currency" text,
"sellingCost" float,
"paymentTerms" varchar,
"salesIncoTerms" varchar,
"estimatedDelivaryDate" date,
"deliverFrom" text,
"deliverTo" text,
"otherEstimatedSalesCostsID" bigint,
"otherActualSalesCostsID" bigint,
"status" text,
"updatedOn" timestamptz,
"updatedBy" bigint,
"salesAgentName" text
);

ALTER TABLE "public"."salesProposal" OWNER TO "postgres";

-- Sales/Purchase proposal linking
CREATE TABLE IF NOT EXISTS "public"."salesPurchaseProposal" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"purchaseProposalID" bigint,
"salesProposalID" bigint,
"conversionRateEURtoUSD" float,
"updatedOn" timestamptz,
"updatedBy" bigint
);

ALTER TABLE "public"."salesPurchaseProposal" OWNER TO "postgres";

-- =====================================================
-- PURCHASE AND SALES ORDERS
-- =====================================================

-- Purchase orders
CREATE TABLE IF NOT EXISTS "public"."purchase" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"CalculationName" varchar,
"poNumber" integer UNIQUE,
"createdAt" timestamptz DEFAULT now(),
"createdBy" bigint,
"updatedAt" timestamptz,
"updatedBy" bigint,
"salesManager" bigint,
"approvedBy" bigint,
"scmManager" bigint,
"status" text,
"active" boolean DEFAULT false,
"checklist" jsonb DEFAULT '[]'::jsonb
);

ALTER TABLE "public"."purchase" OWNER TO "postgres";
COMMENT ON TABLE "public"."purchase" IS 'Stores all purchase orders';

-- Sales orders
CREATE TABLE IF NOT EXISTS "public"."sales" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"CalculationName" varchar,
"soNumber" integer UNIQUE,
"createdAt" timestamptz DEFAULT now(),
"createdBy" bigint,
"soldBy" bigint,
"approvedBy" bigint,
"salesManager" bigint,
"supplyChainManager" bigint,
"active" boolean DEFAULT false,
"checklist" jsonb DEFAULT '[]'::jsonb,
"status" text
);

ALTER TABLE "public"."sales" OWNER TO "postgres";
COMMENT ON TABLE "public"."sales" IS 'Stores all sales orders';

-- =====================================================
-- CONTAINER AND SHIPPING TABLES
-- =====================================================

-- Containers
CREATE TABLE IF NOT EXISTS "public"."containers" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"createdOn" timestamptz DEFAULT now(),
"updatedAt" timestamptz,
"updatedBy" bigint,
"calculationName" text,
"portOfLoading" text,
"portOfDestination" text,
"containerNumber" text,
"BLnumber" text,
"sealNumber" text,
"bookingNumber" text,
"company" bigint,
"dateDepartureConfirmed" boolean DEFAULT false,
"dateArrivalConfirmed" boolean DEFAULT false,
"docCheckListID" bigint
);

ALTER TABLE "public"."containers" OWNER TO "postgres";
COMMENT ON TABLE "public"."containers" IS 'Physical sea containers';

-- Shipping ports
CREATE TABLE IF NOT EXISTS "public"."shippingPorts" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" text UNIQUE,
"UN_LOCODE" text,
"country" text,
"city" text
);

ALTER TABLE "public"."shippingPorts" OWNER TO "postgres";

-- Shipping companies
CREATE TABLE IF NOT EXISTS "public"."shippingCompanies" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" text,
"active" boolean,
"loginURL" text,
"userName" varchar,
"password" varchar,
"comments" text,
"createdBy" bigint,
"updateBy" bigint
);

ALTER TABLE "public"."shippingCompanies" OWNER TO "postgres";

-- Cold storage
CREATE TABLE IF NOT EXISTS "public"."coldStore" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" text,
"contactPersonName" text,
"contactPersonPhoneNumber" integer,
"contactPersonEmail" text,
"webURL" text,
"address" text,
"city" text,
"country" text,
"postCode" varchar,
"active" boolean,
"loginURL" text,
"userName" varchar,
"password" varchar,
"comments" text,
"createdBy" bigint,
"updateBy" bigint
);

ALTER TABLE "public"."coldStore" OWNER TO "postgres";

-- Customs agents
CREATE TABLE IF NOT EXISTS "public"."customsAgent" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" text,
"contactPersonName" text,
"contactPersonPhoneNumber" integer,
"contactPersonEmail" text,
"webURL" text,
"address" text,
"city" text,
"country" text,
"postCode" varchar,
"active" boolean,
"loginURL" text,
"userName" varchar,
"password" varchar,
"comments" text,
"createdBy" bigint,
"updateBy" bigint
);

ALTER TABLE "public"."customsAgent" OWNER TO "postgres";

-- Purchase/Container connections
CREATE TABLE IF NOT EXISTS "public"."purchaseContainersConnections" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"purchaseID" bigint NOT NULL,
"containerID" bigint NOT NULL,
"quantityInContainer" numeric,
"createdAt" timestamptz DEFAULT now(),
"updatedBy" bigint,
CONSTRAINT "purchaseContainersConnections_unique" UNIQUE ("purchaseID", "containerID")
);

ALTER TABLE "public"."purchaseContainersConnections" OWNER TO "postgres";

-- =====================================================
-- ARTICLE AND PRODUCT TABLES
-- =====================================================

-- Articles
CREATE TABLE IF NOT EXISTS "public"."articles" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"articleCode" varchar UNIQUE,
"description" varchar,
"L1Code" integer,
"L2Code" integer,
"L3Code" integer,
"L4Code" integer,
"L5Code" integer,
"L6Code" integer
);

ALTER TABLE "public"."articles" OWNER TO "postgres";

-- Article group/scientific name
CREATE TABLE IF NOT EXISTS "public"."ArticleGroupScientificName" (
"L1Code" integer PRIMARY KEY,
"articleGroup" text,
"scientificName" text,
"hscode" integer
);

ALTER TABLE "public"."ArticleGroupScientificName" OWNER TO "postgres";

-- Article processing
CREATE TABLE IF NOT EXISTS "public"."ArticleProcessing" (
"L1Code" integer UNIQUE,
"L2Code" integer PRIMARY KEY,
"processing" varchar
);

ALTER TABLE "public"."ArticleProcessing" OWNER TO "postgres";

-- Article size
CREATE TABLE IF NOT EXISTS "public"."ArticleSize" (
"L1Code" integer UNIQUE,
"L2Code" integer UNIQUE,
"L3Code" integer PRIMARY KEY,
"size" varchar
);

ALTER TABLE "public"."ArticleSize" OWNER TO "postgres";

-- Article freezing type
CREATE TABLE IF NOT EXISTS "public"."ArticleFreezingType" (
"L4Code" integer PRIMARY KEY,
"freezingType" varchar
);

ALTER TABLE "public"."ArticleFreezingType" OWNER TO "postgres";

-- Article glaze
CREATE TABLE IF NOT EXISTS "public"."ArticleRealGlaze" (
"L5Code" integer,
"realGlaze" integer PRIMARY KEY
);

ALTER TABLE "public"."ArticleRealGlaze" OWNER TO "postgres";

-- Article packaging
CREATE TABLE IF NOT EXISTS "public"."ArticlePackaging" (
"L6Code" integer PRIMARY KEY,
"brand" varchar,
"printedGlaze" integer,
"unitWeight" float,
"BagBoxBulk" text,
"unitsInBox" integer,
"printedPlainRider" text,
"labelsLink" text
);

ALTER TABLE "public"."ArticlePackaging" OWNER TO "postgres";

-- Add unique constraints for article codes
ALTER TABLE "public"."articles" ADD CONSTRAINT "articles_L2Code_unique" UNIQUE ("L2Code");
ALTER TABLE "public"."articles" ADD CONSTRAINT "articles_L3Code_unique" UNIQUE ("L3Code");
ALTER TABLE "public"."articles" ADD CONSTRAINT "articles_L4Code_unique" UNIQUE ("L4Code");
ALTER TABLE "public"."articles" ADD CONSTRAINT "articles_L5Code_unique" UNIQUE ("L5Code");
ALTER TABLE "public"."articles" ADD CONSTRAINT "articles_L6Code_unique" UNIQUE ("L6Code");

-- =====================================================
-- ORDER LINES TABLES
-- =====================================================

-- Purchase order lines
CREATE TABLE IF NOT EXISTS "public"."purchaseOrderLines" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"articlecode" integer,
"purchasePricePerKG" float,
"netWeightKG" float,
"frozenWeightKG" float,
"grossWeight" float,
"createdAt" timestamptz,
"createdBy" bigint,
"updatedAt" timestamptz,
"updatedBy" bigint
);

ALTER TABLE "public"."purchaseOrderLines" OWNER TO "postgres";

-- Sales order lines
CREATE TABLE IF NOT EXISTS "public"."salesOrderLines" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"articleCode" integer,
"salesPricePerKG" integer,
"netWeightKG" float,
"frozenWeightKG" float,
"grossWeight" float,
"createdAt" timestamptz,
"createdBy" bigint,
"updatedAt" timestamptz,
"updatedBy" bigint
);

ALTER TABLE "public"."salesOrderLines" OWNER TO "postgres";

-- Commercial invoice order lines
CREATE TABLE IF NOT EXISTS "public"."commercialInvoiceOrderLines" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"purchaseOrderLineID" bigint,
"articleID" bigint,
"artworkID" bigint,
"netWeightKG" float,
"frozenWeightKG" float,
"grossWeight" float,
"createdAt" timestamptz,
"createdBy" bigint,
"updatedAt" timestamptz,
"updatedBy" bigint
);

ALTER TABLE "public"."commercialInvoiceOrderLines" OWNER TO "postgres";

-- Intake order lines
CREATE TABLE IF NOT EXISTS "public"."intakeOrderLines" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"commercialInvoiceOrderLinesID" bigint,
"coldStoreID" bigint,
"inktakeDate" date,
"poNumber" bigint,
"containerNumber" bigint,
"articleID" bigint,
"artworkID" bigint,
"netWeightKG" float,
"frozenWeightKG" float,
"grossWeight" float,
"createdAt" timestamptz,
"createdBy" bigint,
"updatedAt" timestamptz,
"updatedBy" bigint
);

ALTER TABLE "public"."intakeOrderLines" OWNER TO "postgres";

-- Outtake order lines
CREATE TABLE IF NOT EXISTS "public"."outTakeOrderLines" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"coldStoreID" bigint,
"outakeDate" date,
"salesOrderLineID" bigint,
"articleID" bigint,
"artworkID" bigint,
"netWeightKG" float,
"frozenWeightKG" float,
"grossWeight" float,
"createdAt" timestamptz,
"createdBy" bigint,
"updatedAt" timestamptz,
"updatedBy" bigint
);

ALTER TABLE "public"."outTakeOrderLines" OWNER TO "postgres";

-- =====================================================
-- COST TRACKING TABLES
-- =====================================================

-- Other estimated purchase costs
CREATE TABLE IF NOT EXISTS "public"."otherEstimatedPurchaseCosts" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"agentComission" float,
"purchaseProposalID" bigint,
"freightCosts" float,
"importDuties" float,
"insuranceCosts" float,
"bankCosts" float,
"customsAgentCosts" float,
"inspectionCosts" float
);

ALTER TABLE "public"."otherEstimatedPurchaseCosts" OWNER TO "postgres";

-- Other actual purchase costs
CREATE TABLE IF NOT EXISTS "public"."otherActualPurchaseCosts" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"agentComission" float,
"purchaseProposalID" bigint,
"freightCosts" float,
"importDuties" float,
"insuranceCosts" float,
"bankCosts" float,
"customsAgentCosts" float,
"inspectionCosts" float
);

ALTER TABLE "public"."otherActualPurchaseCosts" OWNER TO "postgres";

-- Other estimated sales costs
CREATE TABLE IF NOT EXISTS "public"."otherEstimatedSalesCosts" (
"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"salesProposalID" bigint,
"coldStoreCosts" float,
"truckCosts" float,
"bankCosts" float,
"insuranceCosts" float,
"salesComission" float
);

ALTER TABLE "public"."otherEstimatedSalesCosts" OWNER TO "postgres";

-- Other actual sales costs
CREATE TABLE IF NOT EXISTS "public"."otherActualSalesCosts" (
"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"salesProposalID" bigint,
"coldStoreCosts" float,
"truckCosts" float,
"bankCosts" float,
"insuranceCosts" float,
"salesComission" float
);

ALTER TABLE "public"."otherActualSalesCosts" OWNER TO "postgres";

-- =====================================================
-- PAYMENT TERMS TABLES
-- =====================================================

-- Customer payment terms
CREATE TABLE IF NOT EXISTS "public"."customerPaymentTerms" (
"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
"code" integer UNIQUE,
"percAdvancePayment" float,
"paymentDays" integer,
"condition" text
);

ALTER TABLE "public"."customerPaymentTerms" OWNER TO "postgres";

-- Supplier payment terms
CREATE TABLE IF NOT EXISTS "public"."supplierPaymentTerms" (
"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
"code" integer UNIQUE,
"percAdvancePayment" float,
"condition" text
);

ALTER TABLE "public"."supplierPaymentTerms" OWNER TO "postgres";

-- =====================================================
-- AGENTS TABLE
-- =====================================================

-- Purchase/Sales agents
CREATE TABLE IF NOT EXISTS "public"."purchaseSalesAgents" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" text UNIQUE,
"contactNumber" bigint,
"country" text,
"salesORpurchaseORboth" text
);

ALTER TABLE "public"."purchaseSalesAgents" OWNER TO "postgres";

-- =====================================================
-- UPDATES TABLE
-- =====================================================

-- Updates/Comments
CREATE TABLE IF NOT EXISTS "public"."updates" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"purchaseID" bigint,
"salesID" bigint,
"containerID" bigint,
"activityStatusID" bigint,
"comment" text NOT NULL,
"updateType" text DEFAULT 'comment',
"updatedBy" bigint,
"createdBy" bigint NOT NULL,
"createdAt" timestamptz DEFAULT now(),
"updatedAt" timestamptz DEFAULT now(),
"isHuman" boolean DEFAULT true,
"isPinned" boolean DEFAULT false,
"originalWorkflowappID" integer UNIQUE,
CONSTRAINT "updates_reference_check" CHECK (
("purchaseID" IS NOT NULL) OR
("salesID" IS NOT NULL) OR
("containerID" IS NOT NULL) OR
("activityStatusID" IS NOT NULL)
)
);

ALTER TABLE "public"."updates" OWNER TO "postgres";
COMMENT ON COLUMN "public"."updates"."isHuman" IS 'Is the update generated by a human?';

-- Add unique constraints for name fields
ALTER TABLE "public"."customers" ADD CONSTRAINT "customers_name_unique" UNIQUE ("name");
ALTER TABLE "public"."suppliers" ADD CONSTRAINT "suppliers_name_unique" UNIQUE ("name");
ALTER TABLE "public"."Calculation" ADD CONSTRAINT "Calculation_name_unique" UNIQUE ("name");

-- =====================================================
-- INDEXES
-- =====================================================

-- Activity indexes
CREATE INDEX IF NOT EXISTS "idx_activityDefinitions_category" ON "public"."activityDefinitions" USING btree ("category");
CREATE INDEX IF NOT EXISTS "idx_activityDefinitions_sort_order" ON "public"."activityDefinitions" USING btree ("activityOrder");
CREATE INDEX IF NOT EXISTS "idx_activityStatus_assigned_to" ON "public"."activityStatus" USING btree ("assignedTo");
CREATE INDEX IF NOT EXISTS "idx_activityStatus_container_id" ON "public"."activityStatus" USING btree ("containerID");
CREATE INDEX IF NOT EXISTS "idx_activityStatus_purchase_id" ON "public"."activityStatus" USING btree ("purchaseID");
CREATE INDEX IF NOT EXISTS "idx_activityStatus_sales_id" ON "public"."activityStatus" USING btree ("salesID");

-- Updates indexes
CREATE INDEX IF NOT EXISTS "idx_updates_activityStatusID" ON "public"."updates" USING btree ("activityStatusID");
CREATE INDEX IF NOT EXISTS "idx_updates_containerID" ON "public"."updates" USING btree ("containerID");
CREATE INDEX IF NOT EXISTS "idx_updates_created_at" ON "public"."updates" USING btree ("createdAt" DESC);
CREATE INDEX IF NOT EXISTS "idx_updates_createdBy" ON "public"."updates" USING btree ("createdBy");
CREATE INDEX IF NOT EXISTS "idx_updates_purchaseID" ON "public"."updates" USING btree ("purchaseID");
CREATE INDEX IF NOT EXISTS "idx_updates_salesID" ON "public"."updates" USING btree ("salesID");
CREATE INDEX IF NOT EXISTS "idx_updates_update_type" ON "public"."updates" USING btree ("updateType");

-- =====================================================
-- FOREIGN KEY CONSTRAINTS
-- =====================================================

-- Activity status foreign keys
ALTER TABLE "public"."activityStatus" ADD FOREIGN KEY ("AssignedTo") REFERENCES "public"."users"("id");
ALTER TABLE "public"."activityStatus" ADD FOREIGN KEY ("completedBy") REFERENCES "public"."users"("id");
ALTER TABLE "public"."activityStatus" ADD FOREIGN KEY ("containerID") REFERENCES "public"."containers"("id");
ALTER TABLE "public"."activityStatus" ADD FOREIGN KEY ("purchaseID") REFERENCES "public"."purchase"("id");
ALTER TABLE "public"."activityStatus" ADD FOREIGN KEY ("salesID") REFERENCES "public"."sales"("id");

-- Container foreign keys
ALTER TABLE "public"."containers" ADD FOREIGN KEY ("calculationName") REFERENCES "public"."Calculation"("name");
ALTER TABLE "public"."containers" ADD FOREIGN KEY ("updatedBy") REFERENCES "public"."users"("id");
ALTER TABLE "public"."containers" ADD FOREIGN KEY ("company") REFERENCES "public"."shippingCompanies"("id");

-- Purchase container connections
ALTER TABLE "public"."purchaseContainersConnections" ADD FOREIGN KEY ("purchaseID") REFERENCES "public"."purchase"("id") ON DELETE CASCADE;
ALTER TABLE "public"."purchaseContainersConnections" ADD FOREIGN KEY ("containerID") REFERENCES "public"."containers"("id") ON DELETE CASCADE;

-- Calculation foreign keys
ALTER TABLE "public"."Calculation" ADD FOREIGN KEY ("createdBy") REFERENCES "public"."users"("id");
ALTER TABLE "public"."Calculation" ADD FOREIGN KEY ("purchaseProposalID") REFERENCES "public"."purchaseProposal"("purchaseProposalID");
ALTER TABLE "public"."Calculation" ADD FOREIGN KEY ("salesProposalID") REFERENCES "public"."salesProposal"("salesProposalID");
ALTER TABLE "public"."Calculation" ADD FOREIGN KEY ("approvedBy") REFERENCES "public"."users"("id");

-- Sales/Purchase proposal linking
ALTER TABLE "public"."salesPurchaseProposal" ADD FOREIGN KEY ("purchaseProposalID") REFERENCES "public"."purchaseProposal"("purchaseProposalID");
ALTER TABLE "public"."salesPurchaseProposal" ADD FOREIGN KEY ("salesProposalID") REFERENCES "public"."salesProposal"("salesProposalID");
ALTER TABLE "public"."salesPurchaseProposal" ADD FOREIGN KEY ("updatedBy") REFERENCES "public"."users"("id");

-- Purchase order foreign keys
ALTER TABLE "public"."purchase" ADD FOREIGN KEY ("CalculationName") REFERENCES "public"."Calculation"("name");
ALTER TABLE "public"."purchase" ADD FOREIGN KEY ("status") REFERENCES "public"."status"("status");

-- Sales order foreign keys
ALTER TABLE "public"."sales" ADD FOREIGN KEY ("CalculationName") REFERENCES "public"."Calculation"("name");
ALTER TABLE "public"."sales" ADD FOREIGN KEY ("status") REFERENCES "public"."status"("status");

-- Article foreign keys
ALTER TABLE "public"."articles" ADD FOREIGN KEY ("L1Code") REFERENCES "public"."ArticleGroupScientificName"("L1Code");
ALTER TABLE "public"."articles" ADD FOREIGN KEY ("L2Code") REFERENCES "public"."ArticleProcessing"("L2Code");
ALTER TABLE "public"."articles" ADD FOREIGN KEY ("L3Code") REFERENCES "public"."ArticleSize"("L3Code");
ALTER TABLE "public"."articles" ADD FOREIGN KEY ("L4Code") REFERENCES "public"."ArticleFreezingType"("L4Code");
ALTER TABLE "public"."articles" ADD FOREIGN KEY ("L5Code") REFERENCES "public"."ArticleRealGlaze"("realGlaze");
ALTER TABLE "public"."articles" ADD FOREIGN KEY ("L6Code") REFERENCES "public"."ArticlePackaging"("L6Code");

-- Article hierarchy foreign keys
ALTER TABLE "public"."ArticleProcessing" ADD FOREIGN KEY ("L1Code") REFERENCES "public"."ArticleGroupScientificName"("L1Code");
ALTER TABLE "public"."ArticleSize" ADD FOREIGN KEY ("L1Code") REFERENCES "public"."ArticleGroupScientificName"("L1Code");
ALTER TABLE "public"."ArticleSize" ADD FOREIGN KEY ("L2Code") REFERENCES "public"."ArticleProcessing"("L2Code");

-- Purchase order lines foreign keys
ALTER TABLE "public"."purchaseOrderLines" ADD FOREIGN KEY ("articlecode") REFERENCES "public"."articles"("articleCode");
ALTER TABLE "public"."purchaseOrderLines" ADD FOREIGN KEY ("createdBy") REFERENCES "public"."users"("id");
ALTER TABLE "public"."purchaseOrderLines" ADD FOREIGN KEY ("updatedBy") REFERENCES "public"."users"("id");

-- Sales order lines foreign keys
ALTER TABLE "public"."salesOrderLines" ADD FOREIGN KEY ("articleCode") REFERENCES "public"."articles"("articleCode");
ALTER TABLE "public"."salesOrderLines" ADD FOREIGN KEY ("createdBy") REFERENCES "public"."users"("id");
ALTER TABLE "public"."salesOrderLines" ADD FOREIGN KEY ("updatedBy") REFERENCES "public"."users"("id");

-- Purchase proposal foreign keys
ALTER TABLE "public"."purchaseProposal" ADD FOREIGN KEY ("purchaseOrderlineID") REFERENCES "public"."purchaseOrderLines"("id");
ALTER TABLE "public"."purchaseProposal" ADD FOREIGN KEY ("supplierName") REFERENCES "public"."suppliers"("name");
ALTER TABLE "public"."purchaseProposal" ADD FOREIGN KEY ("purchaseAgentName") REFERENCES "public"."purchaseSalesAgents"("id");
ALTER TABLE "public"."purchaseProposal" ADD FOREIGN KEY ("otherEstimatedPurchaseCostsID") REFERENCES "public"."otherEstimatedPurchaseCosts"("id");
ALTER TABLE "public"."purchaseProposal" ADD FOREIGN KEY ("otherActualPurchaseCostsID") REFERENCES "public"."otherActualPurchaseCosts"("id");
ALTER TABLE "public"."purchaseProposal" ADD FOREIGN KEY ("portOfLoading") REFERENCES "public"."shippingPorts"("name");
ALTER TABLE "public"."purchaseProposal" ADD FOREIGN KEY ("portOfClerence") REFERENCES "public"."shippingPorts"("name");
ALTER TABLE "public"."purchaseProposal" ADD FOREIGN KEY ("portOfDestination") REFERENCES "public"."shippingPorts"("name");
ALTER TABLE "public"."purchaseProposal" ADD FOREIGN KEY ("status") REFERENCES "public"."status"("status");
ALTER TABLE "public"."purchaseProposal" ADD FOREIGN KEY ("createdBy") REFERENCES "public"."users"("id");
ALTER TABLE "public"."purchaseProposal" ADD FOREIGN KEY ("updatedBy") REFERENCES "public"."users"("id");
ALTER TABLE "public"."purchaseProposal" ADD FOREIGN KEY ("paymentTerms") REFERENCES "public"."supplierPaymentTerms"("code");

-- Sales proposal foreign keys
ALTER TABLE "public"."salesProposal" ADD FOREIGN KEY ("salesOrderlineID") REFERENCES "public"."salesOrderLines"("id");
ALTER TABLE "public"."salesProposal" ADD FOREIGN KEY ("customerName") REFERENCES "public"."customers"("name");
ALTER TABLE "public"."salesProposal" ADD FOREIGN KEY ("salesAgentName") REFERENCES "public"."purchaseSalesAgents"("name");
ALTER TABLE "public"."salesProposal" ADD FOREIGN KEY ("otherEstimatedSalesCostsID") REFERENCES "public"."otherEstimatedSalesCosts"("id");
ALTER TABLE "public"."salesProposal" ADD FOREIGN KEY ("otherActualSalesCostsID") REFERENCES "public"."otherActualSalesCosts"("id");
ALTER TABLE "public"."salesProposal" ADD FOREIGN KEY ("status") REFERENCES "public"."status"("status");
ALTER TABLE "public"."salesProposal" ADD FOREIGN KEY ("updatedBy") REFERENCES "public"."users"("id");
ALTER TABLE "public"."salesProposal" ADD FOREIGN KEY ("paymentTerms") REFERENCES "public"."customerPaymentTerms"("code");

-- Commercial invoice order lines foreign keys
ALTER TABLE "public"."commercialInvoiceOrderLines" ADD FOREIGN KEY ("purchaseOrderLineID") REFERENCES "public"."purchaseOrderLines"("id");
ALTER TABLE "public"."commercialInvoiceOrderLines" ADD FOREIGN KEY ("createdBy") REFERENCES "public"."users"("id");
ALTER TABLE "public"."commercialInvoiceOrderLines" ADD FOREIGN KEY ("updatedBy") REFERENCES "public"."users"("id");

-- Intake order lines foreign keys
ALTER TABLE "public"."intakeOrderLines" ADD FOREIGN KEY ("commercialInvoiceOrderLinesID") REFERENCES "public"."commercialInvoiceOrderLines"("id");
ALTER TABLE "public"."intakeOrderLines" ADD FOREIGN KEY ("coldStoreID") REFERENCES "public"."coldStore"("id");
ALTER TABLE "public"."intakeOrderLines" ADD FOREIGN KEY ("createdBy") REFERENCES "public"."users"("id");
ALTER TABLE "public"."intakeOrderLines" ADD FOREIGN KEY ("updatedBy") REFERENCES "public"."users"("id");

-- Outtake order lines foreign keys
ALTER TABLE "public"."outTakeOrderLines" ADD FOREIGN KEY ("coldStoreID") REFERENCES "public"."coldStore"("id");
ALTER TABLE "public"."outTakeOrderLines" ADD FOREIGN KEY ("salesOrderLineID") REFERENCES "public"."salesOrderLines"("id");
ALTER TABLE "public"."outTakeOrderLines" ADD FOREIGN KEY ("createdBy") REFERENCES "public"."users"("id");
ALTER TABLE "public"."outTakeOrderLines" ADD FOREIGN KEY ("updatedBy") REFERENCES "public"."users"("id");

-- Updates foreign keys
ALTER TABLE "public"."updates" ADD FOREIGN KEY ("purchaseID") REFERENCES "public"."purchase"("id");
ALTER TABLE "public"."updates" ADD FOREIGN KEY ("salesID") REFERENCES "public"."sales"("id");
ALTER TABLE "public"."updates" ADD FOREIGN KEY ("containerID") REFERENCES "public"."containers"("id");
ALTER TABLE "public"."updates" ADD FOREIGN KEY ("activityStatusID") REFERENCES "public"."activityStatus"("id");
ALTER TABLE "public"."updates" ADD FOREIGN KEY ("createdBy") REFERENCES "public"."users"("id");
ALTER TABLE "public"."updates" ADD FOREIGN KEY ("updatedBy") REFERENCES "public"."users"("id");

-- =====================================================
-- ROW LEVEL SECURITY
-- =====================================================

ALTER TABLE "public"."activityDefinitions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."activityStatus" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."containers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."customers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."purchaseContainersConnections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."purchase" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."sales" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."suppliers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."updates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- GRANTS
-- =====================================================

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

-- Grant permissions on all tables
GRANT ALL ON ALL TABLES IN SCHEMA "public" TO "anon";
GRANT ALL ON ALL TABLES IN SCHEMA "public" TO "authenticated";
GRANT ALL ON ALL TABLES IN SCHEMA "public" TO "service_role";

-- Grant permissions on all sequences
GRANT ALL ON ALL SEQUENCES IN SCHEMA "public" TO "anon";
GRANT ALL ON ALL SEQUENCES IN SCHEMA "public" TO "authenticated";
GRANT ALL ON ALL SEQUENCES IN SCHEMA "public" TO "service_role";

-- Default privileges
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";

-- Publication
ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

-- Drop pg_net extension if exists (from remote_schema)
DROP EXTENSION IF EXISTS "pg_net";